# -*- coding: utf-8 -*-
"""pandas_stats.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UUNyH7WmsxvTqGjDCprayKaVQA7EGzBQ

# Phase 2: Descriptive Statistics Using Pandas
## Dataset: 2024 Facebook Political Ads

## Objective

The purpose of this phase is to analyze the same dataset using Pandas and compare a library-based workflow with the pure Python approach from Phase 1.

This notebook includes:
- loading the dataset with Pandas
- checking shape, dtypes, and info()
- generating summary statistics with describe()
- computing missing values by column
- summarizing categorical columns with value_counts() and nunique()
- reviewing parsed numeric columns such as spend, impressions, and estimated audience size
- displaying visualizations in the notebook
"""

import os, ast, warnings
import pandas as pd
import numpy as np
warnings.filterwarnings("ignore")

INPUT_FILE = "/content/fb_ads_president_scored_anon.csv"
DIVIDER = "─" * 72

BINARY_SCORE_COLS = [c for c in [
    "illuminating_scored_message", "illuminating_mentions", "illuminating_scam",
    "illuminating_election_integrity_Truth", "illuminating_msg_type_advocacy",
    "illuminating_msg_type_issue", "illuminating_msg_type_attack",
    "illuminating_msg_type_image", "illuminating_msg_type_cta",
    "illuminating_cta_subtype_engagement", "illuminating_cta_subtype_fundraising",
    "illuminating_cta_subtype_voting", "illuminating_topic_covid",
    "illuminating_topic_economy", "illuminating_topic_education",
    "illuminating_topic_environment", "illuminating_topic_foreign_policy",
    "illuminating_topic_governance", "illuminating_topic_health",
    "illuminating_topic_immigration", "illuminating_topic_lgbtq_issues",
    "illuminating_topic_military", "illuminating_topic_race_and_ethnicity",
    "illuminating_topic_safety", "illuminating_topic_social_and_cultural",
    "illuminating_topic_technology_and_privacy", "illuminating_topic_womens_issue",
    "illuminating_incivility",
]]

RANGE_COLS = ["spend", "impressions", "estimated_audience_size"]
TIME_COLS = ["ad_creation_time", "ad_delivery_start_time", "ad_delivery_stop_time"]
TEXT_COLS  = ["page_name", "bylines", "currency", "publisher_platforms"]


def extract_value(series, key="lower_bound"):
    def _parse(x):
        if pd.isna(x) or not str(x).strip().startswith("{"):
            return np.nan
        try:
            parsed = ast.literal_eval(str(x).strip())
            chosen = parsed.get(key) or parsed.get("lower_bound")
            return float(chosen) if chosen else np.nan
        except Exception:
            return np.nan
    return series.apply(_parse)


def build_range_columns(df):
    for name in RANGE_COLS:
        if name not in df.columns:
            continue
        df[name + "_lower"] = extract_value(df[name], "lower_bound")
        df[name + "_upper"] = extract_value(df[name], "upper_bound")
        df[name + "_mid"] = df.apply(
            lambda row: (row[name + "_lower"] + row[name + "_upper"]) / 2
            if not np.isnan(row.get(name + "_upper", np.nan))
            else row[name + "_lower"], axis=1
        )
    return df


def read_data(file_path):
    if not os.path.exists(file_path):
        print(f"[ERROR] Not found: {file_path}")
        print("Upload fb_ads_president_scored_anon.csv to Colab first.")
        return None
    print(f"  Loading {file_path} …")
    data = pd.read_csv(file_path, low_memory=False)
    print(f"  Loaded: {data.shape[0]:,} rows × {data.shape[1]} columns")
    return data


def show_structure(df):
    print(f"\n{'═'*72}")
    print("  SECTION 1: DATASET STRUCTURE")
    print(f"{'═'*72}")
    print(f"\n  Shape   : {df.shape[0]:,} rows × {df.shape[1]} columns")
    print(f"  Memory  : {df.memory_usage(deep=True).sum() / 1024**2:.1f} MB")
    print(f"\n  Columns and dtypes:")
    for idx, name in enumerate(df.columns, 1):
        missing_count = df[name].isna().sum()
        missing_pct  = missing_count / len(df) * 100
        print(f"    {idx:>3}. {name:<52} {str(df[name].dtype):<10} "
              f"null: {missing_count:>7,} ({missing_pct:4.1f}%)")
    print(f"\n{DIVIDER}")
    print("  info()")
    print(DIVIDER)
    df.info()


def show_missing(df):
    print(f"\n{DIVIDER}")
    print("  SECTION 2: MISSING VALUES")
    print(DIVIDER)
    missing_total = df.isna().sum()
    missing_pct = df.isna().mean() * 100
    cell_count = df.size
    all_missing = missing_total.sum()
    print(f"\n  Total cells    : {cell_count:,}")
    print(f"  Missing cells  : {all_missing:,}  ({all_missing/cell_count*100:.1f}%)")
    print(f"  Rows with any  : {df.isna().any(axis=1).sum():,}")
    print(f"  Rows fully null: {df.isna().all(axis=1).sum():,}")
    print()
    missing_frame = pd.DataFrame({"missing": missing_total, "pct": missing_pct.round(1)})
    missing_frame = missing_frame[missing_frame["missing"] > 0].sort_values("missing", ascending=False)
    print(f"  {'Column':<52} {'Missing':>9} {'%':>7}")
    print(f"  {'─'*52} {'─'*9} {'─'*7}")
    for name, row in missing_frame.iterrows():
        print(f"  {name:<52} {int(row['missing']):>9,} {row['pct']:>6.1f}%")


def show_describe(df):
    print(f"\n{DIVIDER}")
    print("  SECTION 3: describe() OUTPUT")
    print(DIVIDER)

    numeric_desc = df.describe(include=[np.number]).T
    non_numeric_desc = df.describe(include=["object"]).T

    print("\n  Numeric columns:")
    print(numeric_desc)

    print("\n  Non-numeric columns:")
    print(non_numeric_desc)


def show_numeric(df):
    print(f"\n{DIVIDER}")
    print("  SECTION 4: NUMERIC COLUMNS (parsed from dict-strings)")
    print(f"  spend / impressions / estimated_audience_size → lower / midpoint")
    print(DIVIDER)

    parsed_numeric = [c for c in df.columns if c.endswith(("_lower", "_mid", "_upper"))]
    if not parsed_numeric:
        print("  No parsed numeric columns found. Run build_range_columns() first.")
        return

    for name in parsed_numeric:
        series = df[name].dropna()
        print(f"\n  {name}")
        print(f"    count   : {series.count():>12,}")
        print(f"    mean    : {series.mean():>15.2f}")
        print(f"    std     : {series.std():>15.2f}")
        print(f"    std(pop): {series.std(ddof=0):>15.2f}")
        print(f"    min     : {series.min():>15.2f}")
        print(f"    25%     : {series.quantile(0.25):>15.2f}")
        print(f"    median  : {series.median():>15.2f}")
        print(f"    75%     : {series.quantile(0.75):>15.2f}")
        print(f"    max     : {series.max():>15.2f}")
        print(f"    skew    : {series.skew():>15.4f}")
        print(f"    kurt    : {series.kurtosis():>15.4f}")


def show_categorical(df):
    print(f"\n{DIVIDER}")
    print("  SECTION 5: CATEGORICAL COLUMNS")
    print(DIVIDER)

    for name in TEXT_COLS:
        if name not in df.columns:
            continue
        counts = df[name].value_counts(dropna=True)
        valid_n = df[name].notna().sum()
        null_n = df[name].isna().sum()
        unique_n = df[name].nunique()
        print(f"\n  {name}")
        print(f"    non-null : {valid_n:>9,}   missing: {null_n:>7,} ({null_n/len(df)*100:.1f}%)")
        print(f"    unique   : {unique_n:>9,}")
        if not counts.empty:
            mode_val = counts.index[0]
            print(f"    mode     : {str(mode_val)[:55]}  (freq: {counts.iloc[0]:,})")
            print(f"    top 10:")
            for value, count in counts.head(10).items():
                pct = count / valid_n * 100
                shown = (str(value)[:55] + "…") if len(str(value)) > 56 else str(value)
                print(f"      {count:>8,}  ({pct:5.1f}%)  {shown}")

    print(f"\n  Identifier uniqueness:")
    for name in ["page_id", "ad_id"]:
        if name in df.columns:
            print(f"    {name:<30}  unique: {df[name].nunique():,} / {len(df):,}")


def show_spending(df):
    print(f"\n{DIVIDER}")
    print("  SECTION 6: TOP SPENDERS & SPENDING CONCENTRATION")
    print(DIVIDER)

    if "spend_lower" not in df.columns or "page_name" not in df.columns:
        print("  spend_lower column not found. Run build_range_columns() first.")
        return

    grouped = (df.groupby("page_name")["spend_lower"]
                 .agg(total_spend="sum", ad_count="count", avg_spend="mean")
                 .sort_values("total_spend", ascending=False))

    top15 = grouped.head(15)
    overall_spend = grouped["total_spend"].sum()

    print(f"\n  Grand total spend (lower bound) : ${overall_spend:>15,.0f}")
    top1_share  = grouped["total_spend"].head(1).sum() / overall_spend * 100
    top10_share = grouped["total_spend"].head(10).sum() / overall_spend * 100
    top50_share = grouped["total_spend"].head(50).sum() / overall_spend * 100
    print(f"  Top 1  advertisers → {top1_share:5.1f}% of total spend")
    print(f"  Top 10 advertisers → {top10_share:5.1f}% of total spend")
    print(f"  Top 50 advertisers → {top50_share:5.1f}% of total spend")

    print(f"\n  Top 15 Spenders:")
    print(f"  {'Rank':<5} {'Page Name':<50} {'Ads':>7} {'Total $':>14} {'Avg $':>10}")
    print(f"  {'─'*5} {'─'*50} {'─'*7} {'─'*14} {'─'*10}")
    for rank, (page, row) in enumerate(top15.iterrows(), 1):
        shown = (str(page)[:48] + "…") if len(str(page)) > 49 else str(page)
        print(f"  {rank:<5} {shown:<50} {int(row['ad_count']):>7,} "
              f"${row['total_spend']:>13,.0f} ${row['avg_spend']:>9,.0f}")

    spend_series = df["spend_lower"].dropna()
    bins  = [0, 1, 100, 500, 1000, 5000, 10000, 50000, float("inf")]
    labels = ["$0", "$1–99", "$100–499", "$500–999",
              "$1K–4.9K", "$5K–9.9K", "$10K–49.9K", "≥$50K"]
    grouped_bins = pd.cut(spend_series, bins=bins, labels=labels, right=False)
    distribution = grouped_bins.value_counts().reindex(labels)
    print(f"\n  Spend per Ad Distribution (lower bound):")
    for label, count in distribution.items():
        pct = count / len(spend_series) * 100
        print(f"    {label:>12}  {count:>8,}  ({pct:5.1f}%)")


def show_temporal(df):
    print(f"\n{DIVIDER}")
    print("  SECTION 7: TEMPORAL ANALYSIS")
    print(DIVIDER)

    date_name = "ad_delivery_start_time"
    if date_name not in df.columns:
        print("  ad_delivery_start_time not found.")
        return

    parsed_dates = pd.to_datetime(df[date_name], errors="coerce")
    valid_dates = parsed_dates.dropna()
    print(f"\n  Date column : '{date_name}'")
    print(f"  Valid dates : {len(valid_dates):,} / {len(df):,}")
    print(f"  Earliest    : {valid_dates.min().date()}")
    print(f"  Latest      : {valid_dates.max().date()}")
    print(f"  Span        : {(valid_dates.max() - valid_dates.min()).days:,} days")

    temp_df = df.copy()
    temp_df["_month"] = parsed_dates.dt.to_period("M")
    monthly = temp_df.groupby("_month").agg(
        ads=("ad_id", "count"),
        spend=("spend_lower", "sum") if "spend_lower" in temp_df.columns else ("page_id", "count")
    ).reset_index().sort_values("_month")

    print(f"\n  Monthly Ad Activity:")
    print(f"  {'Month':<10} {'Ads':>8}  {'Spend (LB)':>14}")
    print(f"  {'─'*10} {'─'*8}  {'─'*14}")
    for _, row in monthly.iterrows():
        spend_text = f"${row['spend']:>13,.0f}" if "spend_lower" in temp_df.columns else ""
        print(f"  {str(row['_month']):<10} {int(row['ads']):>8,}  {spend_text:>15}")

    events = {
        "2024-03-05": "Super Tuesday",
        "2024-06-27": "Debate 1 (Trump vs Biden)",
        "2024-07-21": "Biden withdraws",
        "2024-09-10": "Debate 2 (Trump vs Harris)",
        "2024-10-01": "VP Debate",
        "2024-11-05": "Election Day",
    }
    print(f"\n  Ads within ±7 days of key 2024 events:")
    for dstr, label in events.items():
        event_day = pd.Timestamp(dstr)
        mask = (parsed_dates >= event_day - pd.Timedelta(days=7)) & (parsed_dates <= event_day + pd.Timedelta(days=7))
        print(f"    {dstr}  {label:<35}  {mask.sum():>7,} ads")


def show_illuminating(df):
    print(f"\n{DIVIDER}")
    print("  SECTION 8: ILLUMINATING BINARY SCORED COLUMNS (28 columns)")
    print(f"  Showing prevalence (% of ads flagged 1)")
    print(DIVIDER)

    available_cols = [c for c in BINARY_SCORE_COLS if c in df.columns]
    if not available_cols:
        print("  No illuminating columns found.")
        return

    print(f"\n  {'Label':<50} {'Flagged':>9} {'%':>7}  {'Missing':>8}")
    print(f"  {'─'*50} {'─'*9} {'─'*7}  {'─'*8}")
    summary_rows = []
    for name in available_cols:
        numeric_vals = pd.to_numeric(df[name], errors="coerce")
        one_total = (numeric_vals == 1).sum()
        missing_n = numeric_vals.isna().sum()
        valid_n = len(numeric_vals) - missing_n
        pct_flagged = one_total / valid_n * 100 if valid_n else 0
        cleaned_name = name.replace("illuminating_", "")
        summary_rows.append((cleaned_name, one_total, pct_flagged, missing_n))

    for cleaned_name, one_total, pct_flagged, missing_n in sorted(summary_rows, key=lambda x: x[2], reverse=True):
        print(f"  {cleaned_name:<50} {one_total:>9,} {pct_flagged:>6.1f}%  {missing_n:>8,}")

    topic_cols = [c for c in available_cols if "topic" in c]
    if topic_cols:
        topic_df = df[topic_cols].apply(pd.to_numeric, errors="coerce").fillna(0)
        topic_count = topic_df.sum(axis=1)
        print(f"\n  Topic co-occurrence per ad:")
        for n in range(0, 6):
            count = (topic_count == n).sum()
            print(f"    {n} topics flagged : {count:>8,}  ({count/len(df)*100:.1f}%)")
        print(f"    6+ topics flagged: {(topic_count >= 6).sum():>8,}  "
              f"({(topic_count >= 6).sum()/len(df)*100:.1f}%)")


def create_visuals(df, out_dir="visualizations"):
    try:
        import matplotlib.pyplot as plt
        import matplotlib.ticker as mtick
    except ImportError:
        print("\nInstall matplotlib to save plots.")
        return

    os.makedirs(out_dir, exist_ok=True)
    print(f"\n{DIVIDER}")
    print(f"  GENERATING VISUALIZATIONS → {out_dir}/")
    print(DIVIDER)

    if "spend_lower" in df.columns:
        spend_values = df["spend_lower"].dropna()
        positive_spend = spend_values[spend_values > 0]

        fig, ax = plt.subplots(figsize=(10, 5))
        ax.hist(positive_spend.clip(upper=positive_spend.quantile(0.99)),
                bins=50, edgecolor="black", alpha=0.8)
        ax.set_title("Distribution of Ad Spend (Lower Bound)")
        ax.set_xlabel("Spend Lower Bound ($)")
        ax.set_ylabel("Number of Ads")
        ax.xaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f"${x:,.0f}"))
        plt.tight_layout()
        path = f"{out_dir}/plot_01_spend_histogram.png"
        plt.savefig(path, dpi=150, bbox_inches="tight")
        plt.close()
        print(f"  ✓ {path}")

    if "spend_lower" in df.columns and "page_name" in df.columns:
        top_pages = (df.groupby("page_name")["spend_lower"]
                     .sum()
                     .sort_values(ascending=False)
                     .head(12))

        fig, ax = plt.subplots(figsize=(12, 6))
        ax.bar(range(len(top_pages)), top_pages.values)
        ax.set_title("Top 12 Pages by Total Spend")
        ax.set_ylabel("Total Spend Lower Bound ($)")
        ax.set_xticks(range(len(top_pages)))
        ax.set_xticklabels([str(x)[:35] for x in top_pages.index], rotation=45, ha="right")
        ax.yaxis.set_major_formatter(mtick.FuncFormatter(
            lambda x, _: f"${x/1e6:.1f}M" if x >= 1e6 else f"${x:,.0f}"))
        plt.tight_layout()
        path = f"{out_dir}/plot_02_top_spenders_bar.png"
        plt.savefig(path, dpi=150, bbox_inches="tight")
        plt.close()
        print(f"  ✓ {path}")

    if "ad_delivery_start_time" in df.columns:
        date_series = pd.to_datetime(df["ad_delivery_start_time"], errors="coerce")
        chart_df = df.copy()
        chart_df["month_key"] = date_series.dt.to_period("M")
        monthly_counts = chart_df.groupby("month_key").size().reset_index(name="ads")
        monthly_counts["month_dt"] = monthly_counts["month_key"].dt.to_timestamp()

        fig, ax = plt.subplots(figsize=(12, 5))
        ax.plot(monthly_counts["month_dt"], monthly_counts["ads"], marker="o", linewidth=2)
        ax.set_title("Monthly Ad Volume")
        ax.set_xlabel("Month")
        ax.set_ylabel("Number of Ads")
        ax.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f"{x:,.0f}"))
        plt.tight_layout()
        path = f"{out_dir}/plot_03_monthly_ads_line.png"
        plt.savefig(path, dpi=150, bbox_inches="tight")
        plt.close()
        print(f"  ✓ {path}")

    topic_columns = [c for c in BINARY_SCORE_COLS if "topic" in c and c in df.columns]
    if topic_columns:
        topic_percent = {
            c.replace("illuminating_topic_", ""):
            pd.to_numeric(df[c], errors="coerce").mean() * 100
            for c in topic_columns
        }
        topic_series = pd.Series(topic_percent).sort_values(ascending=False)

        fig, ax = plt.subplots(figsize=(10, 6))
        ax.barh(topic_series.index, topic_series.values)
        ax.set_title("Topic Prevalence in Ads")
        ax.set_xlabel("% of Ads Flagged")
        ax.invert_yaxis()
        ax.xaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f"{x:.1f}%"))
        plt.tight_layout()
        path = f"{out_dir}/plot_04_topic_prevalence.png"
        plt.savefig(path, dpi=150, bbox_inches="tight")
        plt.close()
        print(f"  ✓ {path}")

    message_cols = [c for c in BINARY_SCORE_COLS if "msg_type" in c and c in df.columns]
    if message_cols:
        message_counts = {
            c.replace("illuminating_msg_type_", ""):
            pd.to_numeric(df[c], errors="coerce").sum()
            for c in message_cols
        }
        message_series = pd.Series(message_counts).sort_values(ascending=False)

        fig, ax = plt.subplots(figsize=(8, 4))
        ax.bar(message_series.index, message_series.values)
        ax.set_title("Message Type Counts")
        ax.set_xlabel("Message Type")
        ax.set_ylabel("Number of Ads")
        ax.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f"{x:,.0f}"))
        plt.xticks(rotation=30, ha="right")
        plt.tight_layout()
        path = f"{out_dir}/plot_05_message_types.png"
        plt.savefig(path, dpi=150, bbox_inches="tight")
        plt.close()
        print(f"  ✓ {path}")

df = read_data(INPUT_FILE)
if df is not None:
    print("  Parsing dict-string columns (spend / impressions / audience) …")
    df = build_range_columns(df)

    show_structure(df)
    show_missing(df)
    show_describe(df)
    show_numeric(df)
    show_categorical(df)
    show_spending(df)
    show_temporal(df)
    show_illuminating(df)

create_visuals(df)

import shutil
from google.colab import files

shutil.make_archive("visualizations", "zip", "visualizations")
files.download("visualizations.zip")