# -*- coding: utf-8 -*-
"""pure_python_stats.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19LcIOBtmEXnaaHj05B0vNZOsL0cFFpEt

# Phase 1: Descriptive Statistics (Pure Python)
## Dataset: 2024 Facebook Political Ads

## Objective

The goal of this task is to explore and summarize a real-world dataset using only Python’s standard library (no Pandas or NumPy).

This includes:
- Loading and parsing CSV data
- Computing descriptive statistics manually
- Handling missing values and data inconsistencies
- Generating summaries for numeric and categorical columns

## Dataset Overview

The dataset contains Facebook political ads from the 2024 U.S. Presidential election.

Each row represents an ad and includes:
- Ad metadata (page name, platform, timestamps)
- Estimated impressions and spend (stored as ranges)
- Audience size estimates
- Binary indicators for topics and messaging

Some columns (like spend and impressions) are stored as ranges:
{'lower_bound': '...', 'upper_bound': '...'}

For analysis, the midpoint or lower bound is used as a numeric approximation.
"""

CSV_FILE = "/content/fb_ads_president_scored_anon.csv"

import csv
import math
import collections
import os
import ast
from datetime import datetime

# ================================================================

INPUT_FILE = "/content/fb_ads_president_scored_anon.csv"
DIVIDER = "─" * 72

# The 28 illuminating binary columns
FLAG_COLUMNS = [
    "illuminating_scored_message", "illuminating_mentions", "illuminating_scam",
    "illuminating_election_integrity_Truth", "illuminating_msg_type_advocacy",
    "illuminating_msg_type_issue", "illuminating_msg_type_attack",
    "illuminating_msg_type_image", "illuminating_msg_type_cta",
    "illuminating_cta_subtype_engagement", "illuminating_cta_subtype_fundraising",
    "illuminating_cta_subtype_voting", "illuminating_topic_covid",
    "illuminating_topic_economy", "illuminating_topic_education",
    "illuminating_topic_environment", "illuminating_topic_foreign_policy",
    "illuminating_topic_governance", "illuminating_topic_health",
    "illuminating_topic_immigration", "illuminating_topic_lgbtq_issues",
    "illuminating_topic_military", "illuminating_topic_race_and_ethnicity",
    "illuminating_topic_safety", "illuminating_topic_social_and_cultural",
    "illuminating_topic_technology_and_privacy", "illuminating_topic_womens_issue",
    "illuminating_incivility",
]

# Dict-string columns (spend/impressions/audience stored as {'lower_bound':...})
RANGE_COLUMNS = ["estimated_audience_size", "impressions", "spend"]

TIME_COLUMNS = ["ad_creation_time", "ad_delivery_start_time", "ad_delivery_stop_time"]

TEXT_COLUMNS = ["page_name", "bylines", "currency", "publisher_platforms"]


# ================================================================
# Helper functions
# ================================================================
def value_is_missing(x):
    return x is None or str(x).strip() in ("", "nan", "NaN", "None", "N/A", "NA")


def to_float_safe(x):
    """Return (float, True) or (None, False)."""
    if value_is_missing(x):
        return None, False
    try:
        return float(str(x).strip().replace(",", "")), True
    except ValueError:
        return None, False


def parse_range_text(text):
    """
    Parse Meta Ad Library dict-strings like:
      "{'lower_bound': '45000', 'upper_bound': '49999'}"
    Returns dict or None on failure.
    """
    if value_is_missing(text):
        return None
    try:
        return ast.literal_eval(text.strip())
    except Exception:
        return None


def get_range_bounds(text):
    """
    From a dict-string, return (lower_float, upper_float).
    If upper_bound missing (open-ended like ≥1,000,001), upper = lower.
    """
    parsed = parse_range_text(text)
    if parsed is None:
        return None, None
    lower_val, lower_ok = to_float_safe(parsed.get("lower_bound", ""))
    upper_val, upper_ok = to_float_safe(parsed.get("upper_bound", ""))
    lower = lower_val if lower_ok else None
    upper = upper_val if upper_ok else (lower if lower is not None else None)
    return lower, upper


# ================================================================
#  Sttaitics functions
# ================================================================
def calc_mean(nums):
    return sum(nums) / len(nums) if nums else None


def calc_std_population(nums):
    if len(nums) < 2:
        return None
    avg = calc_mean(nums)
    return math.sqrt(sum((x - avg) ** 2 for x in nums) / len(nums))


def calc_median(nums):
    if not nums:
        return None
    sorted_vals = sorted(nums)
    size = len(sorted_vals)
    middle = size // 2
    return (sorted_vals[middle - 1] + sorted_vals[middle]) / 2.0 if size % 2 == 0 else float(sorted_vals[middle])


def calc_percentile(nums, pct):
    if not nums:
        return None
    sorted_vals = sorted(nums)
    index = (pct / 100.0) * (len(sorted_vals) - 1)
    lower_i, upper_i = int(index), int(index) + 1
    fraction = index - lower_i
    return sorted_vals[lower_i] if upper_i >= len(sorted_vals) else sorted_vals[lower_i] + fraction * (sorted_vals[upper_i] - sorted_vals[lower_i])


def summarize_numeric(column_values):
    """Full stats dict from a list of raw strings or floats."""
    clean_values, missing_count = [], 0
    for x in column_values:
        num, ok = to_float_safe(x)
        if ok:
            clean_values.append(num)
        else:
            missing_count += 1
    if not clean_values:
        return dict(count=0, missing=missing_count, mean=None, std=None,
                    median=None, min=None, max=None, q25=None, q75=None)
    return dict(
        count=len(clean_values), missing=missing_count,
        mean=calc_mean(clean_values), std=calc_std_population(clean_values),
        median=calc_median(clean_values), min=min(clean_values), max=max(clean_values),
        q25=calc_percentile(clean_values, 25), q75=calc_percentile(clean_values, 75),
    )


def summarize_categorical(column_values, top_n=5):
    filled_values, missing_count = [], 0
    for x in column_values:
        if value_is_missing(x):
            missing_count += 1
        else:
            filled_values.append(str(x).strip())
    if not filled_values:
        return dict(count=0, missing=missing_count, unique=0,
                    mode=None, mode_freq=0, top_values=[])
    freq_map = collections.Counter(filled_values)
    top_items = freq_map.most_common(top_n)
    return dict(count=len(filled_values), missing=missing_count, unique=len(freq_map),
                mode=top_items[0][0], mode_freq=top_items[0][1], top_values=top_items)


# ================================================================
# PRINT
# ================================================================
def format_value(x, dec=2):
    if x is None:
        return "N/A"
    if isinstance(x, float):
        return f"{x:,.{dec}f}"
    return str(x)


def display_numeric(label, stats, total_count):
    pct_missing = stats["missing"] / total_count * 100 if total_count else 0
    print(f"\n  ┌ {label}  [numeric]")
    print(f"  │  non-null: {stats['count']:>9,}  missing: {stats['missing']:>7,} ({pct_missing:.1f}%)")
    print(f"  │  mean    : {format_value(stats['mean']):>14}   std    : {format_value(stats['std']):>14}")
    print(f"  │  min     : {format_value(stats['min']):>14}   max    : {format_value(stats['max']):>14}")
    print(f"  │  Q25     : {format_value(stats['q25']):>14}   median : {format_value(stats['median']):>14}   Q75: {format_value(stats['q75'])}")
    print(f"  └{'─'*60}")


def display_categorical(label, stats, total_count):
    pct_missing = stats["missing"] / total_count * 100 if total_count else 0
    print(f"\n  ┌ {label}  [categorical]")
    print(f"  │  non-null: {stats['count']:>9,}  missing: {stats['missing']:>7,} ({pct_missing:.1f}%)")
    print(f"  │  unique  : {stats['unique']:>9,}  mode   : {(str(stats['mode'])[:45] if stats['mode'] else 'N/A')}")
    print(f"  │  top values:")
    for val, cnt in stats["top_values"]:
        pct = cnt / stats["count"] * 100 if stats["count"] else 0
        shown = (str(val)[:55] + "…") if len(str(val)) > 56 else str(val)
        print(f"  │    {cnt:>8,}  ({pct:5.1f}%)  {shown}")
    print(f"  └{'─'*60}")


# ================================================================
# Reding thefile
# ================================================================
def read_dataset(file_path):
    if not os.path.exists(file_path):
        print(f"\n[ERROR] File not found: {file_path}")
        print("  Upload fb_ads_president_scored_anon.csv to Colab first.")
        return None, None, 0

    columns_data = collections.OrderedDict()
    row_count = 0
    print(f"  Reading: {file_path}  (this may take ~30 sec for 246K rows) …")

    with open(file_path, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        column_names = reader.fieldnames or []
        for col in column_names:
            columns_data[col] = []
        for row in reader:
            row_count += 1
            for col in column_names:
                columns_data[col].append(row.get(col, ""))
            if row_count % 50000 == 0:
                print(f"    … {row_count:,} rows loaded")

    print(f"  Done. {row_count:,} rows × {len(column_names)} columns")
    return column_names, columns_data, row_count


# ================================================================
# MAIN ANALYSIS
# ================================================================
def run_analysis(file_path=INPUT_FILE):
    print(f"\n{'═'*72}")
    print("  Descriptive statitics using pure Python")
    print("  Dataset: fb_ads_president_scored_anon.csv")
    print(f"{'═'*72}")

    column_names, columns_data, total_rows = read_dataset(file_path)
    if column_names is None:
        return

    print(f"\n{DIVIDER}")
    print("  Data Overview ")
    print(DIVIDER)
    print(f"  Rows    : {total_rows:,}")
    print(f"  Columns : {len(column_names)}")
    print()

    print(f"  {'Column':<48} {'Missing':>8}  {'%':>6}")
    print(f"  {'─'*48} {'─'*8}  {'─'*6}")
    for col in column_names:
        missing_total = sum(1 for x in columns_data[col] if value_is_missing(x))
        pct = missing_total / total_rows * 100 if total_rows else 0
        short_name = (col[:46] + "…") if len(col) > 47 else col
        print(f"  {short_name:<48} {missing_total:>8,}  {pct:>5.1f}%")

    print(f"\n{DIVIDER}")
    print("  Categorical columns ")
    print(DIVIDER)
    for col in TEXT_COLUMNS:
        if col in columns_data:
            stats = summarize_categorical(columns_data[col])
            display_categorical(col, stats, total_rows)

    print(f"\n  Identifier cardinality:")
    for col in ["page_id", "ad_id"]:
        if col in columns_data:
            unique_total = len(set(x for x in columns_data[col] if not value_is_missing(x)))
            print(f"    {col:<30}  unique: {unique_total:,}")

    print(f"\n{DIVIDER}")
    print("  Date columns")
    print(DIVIDER)
    for col in TIME_COLUMNS:
        if col not in columns_data:
            continue
        parsed_dates, missing_total = [], 0
        for x in columns_data[col]:
            if value_is_missing(x):
                missing_total += 1
                continue
            try:
                parsed_dates.append(datetime.strptime(x.strip()[:10], "%Y-%m-%d"))
            except ValueError:
                missing_total += 1
        if parsed_dates:
            print(f"\n  {col}")
            print(f"    non-null : {len(parsed_dates):,}  missing: {missing_total:,}")
            print(f"    earliest : {min(parsed_dates).date()}")
            print(f"    latest   : {max(parsed_dates).date()}")
            span_days = (max(parsed_dates) - min(parsed_dates)).days
            print(f"    span     : {span_days:,} days")

    print(f"\n{DIVIDER}")
    print("  Dict-string columns: spend / impressions / estimated_audience_size")
    print(f"  (Each stored as {{'lower_bound': '...', 'upper_bound': '...'}})")
    print(DIVIDER)

    for col in RANGE_COLUMNS:
        if col not in columns_data:
            continue
        lower_vals, upper_vals, midpoint_vals, missing_total = [], [], [], 0
        for x in columns_data[col]:
            low, high = get_range_bounds(x)
            if low is None:
                missing_total += 1
            else:
                lower_vals.append(low)
                if high is not None:
                    upper_vals.append(high)
                midpoint_vals.append((low + (high or low)) / 2.0)

        print(f"\n  {col}  (parsed lower bounds):")
        lower_stats = summarize_numeric(lower_vals)
        lower_stats["missing"] = missing_total
        display_numeric(col + " [lower_bound]", lower_stats, total_rows)

        print(f"  {col}  (midpoint estimates):")
        midpoint_stats = summarize_numeric(midpoint_vals)
        midpoint_stats["missing"] = missing_total
        display_numeric(col + " [midpoint]", midpoint_stats, total_rows)

        if col == "spend" and lower_vals:
            spend_buckets = collections.Counter()
            for x in lower_vals:
                if x == 0:
                    spend_buckets["$0"] += 1
                elif x < 100:
                    spend_buckets["$1–99"] += 1
                elif x < 500:
                    spend_buckets["$100–499"] += 1
                elif x < 1000:
                    spend_buckets["$500–999"] += 1
                elif x < 5000:
                    spend_buckets["$1K–4.9K"] += 1
                elif x < 10000:
                    spend_buckets["$5K–9.9K"] += 1
                elif x < 50000:
                    spend_buckets["$10K–49.9K"] += 1
                else:
                    spend_buckets["≥$50K"] += 1
            total_spend_rows = len(lower_vals)
            print(f"\n  Spend Distribution (lower_bound):")
            for bucket in ["$0", "$1–99", "$100–499", "$500–999",
                           "$1K–4.9K", "$5K–9.9K", "$10K–49.9K", "≥$50K"]:
                cnt = spend_buckets.get(bucket, 0)
                pct = cnt / total_spend_rows * 100 if total_spend_rows else 0

                print(f"    {bucket:>12}  {cnt:>8,}  ({pct:5.1f}%)  ")

    print(f"\n{DIVIDER}")
    print("  Top 15 Spenders  (by page_name, summing spend lower_bound)")
    print(DIVIDER)
    if "page_name" in columns_data and "spend" in columns_data:
        spend_by_page = collections.defaultdict(float)
        ads_by_page = collections.defaultdict(int)
        for i in range(total_rows):
            page = columns_data["page_name"][i].strip() if not value_is_missing(columns_data["page_name"][i]) else "Unknown"
            low, _ = get_range_bounds(columns_data["spend"][i])
            if low is not None:
                spend_by_page[page] += low
                ads_by_page[page] += 1
        top_pages = sorted(spend_by_page.items(), key=lambda x: x[1], reverse=True)[:15]
        print(f"\n  {'Rank':<5} {'Page Name':<50} {'Ads':>7} {'Total Spend (LB)':>18}")
        print(f"  {'─'*5} {'─'*50} {'─'*7} {'─'*18}")
        for rank, (page, total_spend) in enumerate(top_pages, 1):
            short_page = (page[:48] + "…") if len(page) > 49 else page
            print(f"  {rank:<5} {short_page:<50} {ads_by_page[page]:>7,} ${total_spend:>17,.0f}")

    print(f"\n{DIVIDER}")
    print("  Illuminating scored columns  (binary 0/1, % of valid rows flagged)")
    print(DIVIDER)
    print(f"\n  {'Column':<50} {'Flagged (=1)':>12} {'%':>7}  {'Missing':>8}")
    print(f"  {'─'*50} {'─'*12} {'─'*7}  {'─'*8}")
    for col in FLAG_COLUMNS:
        if col not in columns_data:
            continue
        one_count, zero_count, missing_total = 0, 0, 0
        for x in columns_data[col]:
            if value_is_missing(x):
                missing_total += 1
            elif str(x).strip() in ("1", "1.0", "True", "true"):
                one_count += 1
            else:
                zero_count += 1
        valid_total = one_count + zero_count
        pct = one_count / valid_total * 100 if valid_total else 0
        label = col.replace("illuminating_", "")
        print(f"  {label:<50} {one_count:>12,} {pct:>6.1f}%  {missing_total:>8,}")

    print(f"\n{DIVIDER}")
    print("  Temporal analysis — Monthly Ad Volume")
    print(DIVIDER)
    if "ad_delivery_start_time" in columns_data:
        monthly_counts = collections.Counter()
        monthly_spend = collections.defaultdict(float)
        for i, x in enumerate(columns_data["ad_delivery_start_time"]):
            if value_is_missing(x):
                continue
            try:
                dt = datetime.strptime(x.strip()[:10], "%Y-%m-%d")
                month_key = dt.strftime("%Y-%m")
                monthly_counts[month_key] += 1
                low, _ = get_range_bounds(columns_data["spend"][i]) if "spend" in columns_data else (None, None)
                if low is not None:
                    monthly_spend[month_key] += low
            except ValueError:
                pass
        if monthly_counts:
            max_count = max(monthly_counts.values())
            print(f"\n  {'Month':<10} {'Ads':>8}  {'Spend (LB $)':>14}  Chart")
            print(f"  {'─'*10} {'─'*8}  {'─'*14}  {'─'*35}")
            for month in sorted(monthly_counts):
                count = monthly_counts[month]
                spend_total = monthly_spend.get(month, 0)

                print(f"  {month:<10} {count:>8,}  ${spend_total:>13,.0f} ")

    print(f"\n{'═'*72}")
    print(" Analysis completed ")
    print(f"{'═'*72}\n")

run_analysis()